Bailey/#15 login controller
bill-luu/ENSF-480-Project pull request #23
Opened 2017-11-14 04:41 UTC by BKDuncan

LoginController finished and data classes updated.

2017-11-15 05:36 UTC, bill-luu requested changes

2017-11-15 05:36 UTC, bill-luu commented on src/business/LoginController.java
> +        	if(validLogin.matches("dev-<" + login + ">")){
There's no password check here.

2017-11-15 05:36 UTC, bill-luu commented on src/data/Bug.java
> +	enum State {pending_approval, rejected, awaiting_assignment, in_progress, fixed};
Let's follow conventions on Enum naming, so `PENDING_APPROVAL, REJECTED, etc`
https://stackoverflow.com/questions/3069743/coding-conventions-naming-enums

2017-11-15 05:56 UTC, bill-luu requested changes

2017-11-15 05:56 UTC, bill-luu commented on src/business/LoginController.java
> +        	if(validLogin.matches("dev-<" + login + ">")){
Disregard!

2017-11-15 05:56 UTC, bill-luu commented on src/business/LoginController.java
> +        	if(validLogin.matches("dev-<" + login + ">")){
We should update the sample in this PR

2017-11-15 15:50 UTC, bill-luu requested changes

2017-11-15 15:50 UTC, bill-luu commented on src/data/Bug.java
> +	 * Enum for bug state. Can be pending_approval, awaiting_assignment, in_progress, rejected, or fixed.
Update this comment too!

2017-11-16 23:09 UTC, bill-luu approved these changes

2017-11-16 23:09 UTC, bill-luu commented
LGTM

2017-11-16 23:18 UTC, a-sood approved these changes
Looks good

2017-11-16 23:19 UTC, merged